# Generated by Django 5.1.4 on 2025-01-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_rename_content_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='comment_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='post_pics'),
        ),
    ]
