# Generated by Django 5.1.4 on 2025-01-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_rename_profile_picture_post_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile_pic',
        ),
    ]
